ALTER TYPE "UserRole" RENAME VALUE 'OWNER' TO 'ADMIN';
ALTER TYPE "UserRole" RENAME VALUE 'MEMBER' TO 'USER';

UPDATE "User" SET "role" = 'USER' WHERE "role" = 'ADMIN';

ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'USER';
